#Check if OpenMP is present
if (NOT openmp)
    message("--OpenMP disabled")
else()
    find_package(OpenMP)
    if (openmp AND OPENMP_FOUND)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
        set(REQUIRED_CXX_FLAGS "${REQUIRED_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    else()
        message("--OpenMP not found, parallelisation will be disabled")
        return()
    endif()
endif()
