#!/usr/bin/env python
"""
SCRIPT: input_to_sevn2
PURPOSE: Take an input file written with the SEVN1 legacy style and transform to SEVN2  style
USAGE; ./input_to_sevn2 input <PATH_TO_THE_SEVN2STYLE_INPUT> outputname  <PATH_TO_THE_SEVN2STYLE_TO_SAVE> [Optional]
e.g. ./input_to_sevn2 listBin.dat  listBin_v2.dat
Note: If the outputname is not given the default output will be input_sevn2.dat
REQUIRED PACKAGE:
    -pandas

V 1.0: 22/03/21 Giuliano Iorio
"""


import pandas as pd
import sys



Header_SEVN2=("M1", "Z1", "Spin1","SN1", "Tstart1","M2","Z2","Spin2","SN2","Tstart2","a","e","Tend","dtout","Rseed")
Header_SEVN1=("M1", "M2", "Z1","Z2", "Spin1","Spin2","a","e","Tend","Tstart","dt","SN1","SN2","dtout","Rseed")

if __name__=="__main__":

    argv = sys.argv

    if len(argv)==1:
        raise IOError("Please write the PATH to the input file")
    elif len(argv)==2:
        input_file=sys.argv[1]
        output_name=sys.argv[1].split(".")[0]+"_sevn2.dat"
    elif len(argv)==3:
        input_file, output_name=sys.argv[1:]
    else:
        raise IOError("Maximum number of script parameters is 2, you give %i parameters"%(len(argv)-1))


    data = pd.read_csv(input_file,delimiter="\s+",engine="python",header=None,names=Header_SEVN1)
    data["Tstart1"]=data["Tstart"]
    data["Tstart2"]=data["Tstart"]
    data[list(Header_SEVN2)].to_csv(output_name,sep=" ",na_rep='',header=False,index=False)

